spring:
  application:
    name: spring-ai-chat

  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: never
        timeout: 5m
      chat:
        model: llama3.2:3b
        format:
    embedding:
      model: ollama
      ollama:
        base-url: http://localhost:11434
        embedding-model: mxbai-embed-large
        init:
          pull-model-strategy: never
          timeout: 5m
    vectorstore:
      qdrant:
        host: localhost
        port: 6333
        grpc-port: 6334
        collection-name: spring-ai-demo
        initialize-schema: false

  datasource:
    url: jdbc:postgresql://localhost:5432/spring-ai
    username: myapp
    password: myapp

  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    resource:
      attributes:
        service.name: spring-ai-chat
        service.version: 0.0.1
        deployment.environment: local
        service.instance.id: instance-1
        job.name: chat-service
        application.name: "${spring.application.name}"
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
  tracing:
    sampling:
      probability: 1.0